# syntax=docker/dockerfile:1
# Plant Pal — FastAPI + uvicorn. Data: mount a volume on /app/data for SQLite persistence.
#
# Local test (Mac/Linux):
#   docker build -t plant-pal:local .
#   docker run --rm -p 127.0.0.1:8000:8000 -v plantpal-data:/app/data plant-pal:local
#   open http://127.0.0.1:8000
#
# Push for Raspberry Pi (ARM64), from your dev machine:
#   docker buildx create --use   # once per machine, if you have no builder
#   docker buildx build --platform linux/arm64 -t YOUR_REGISTRY/plant-pal:latest --push .
#
# Multi-platform (amd64 + arm64) so one tag works on desktop and Pi:
#   docker buildx build --platform linux/amd64,linux/arm64 -t YOUR_REGISTRY/plant-pal:latest --push .
#
# Dependency story:
#   Installs are hash-verified from requirements.lock (generated by
#   `make lock` / `make upgrade`). --require-hashes means a tampered or
#   drifted wheel fails the build loudly rather than silently producing a
#   different image. Keep requirements.lock in source control.

FROM python:3.12-slim-bookworm AS builder

WORKDIR /app

# Build tools are sometimes needed for wheels without ARM64 pre-builds.
# Keep them in the builder stage only; the runtime image stays slim.
RUN apt-get update \
    && apt-get install --no-install-recommends -y build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.lock .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir --require-hashes -r requirements.lock

FROM python:3.12-slim-bookworm AS runtime

RUN useradd --create-home --uid 1000 --shell /usr/sbin/nologin plantpal

WORKDIR /app

ENV PATH="/opt/venv/bin:$PATH" \
    PLANTPAL_HOST=0.0.0.0 \
    PLANTPAL_PORT=8000 \
    PLANTPAL_LOG_LEVEL=INFO \
    PLANTPAL_LOG_FORMAT=text \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
# Optional: set at deploy time so /status can show which build is running.
#   -e PLANTPAL_GIT_SHA=$(git rev-parse --short HEAD)

COPY --from=builder /opt/venv /opt/venv

COPY --chown=plantpal:plantpal . .

RUN mkdir -p /app/data && chown plantpal:plantpal /app/data

USER plantpal

EXPOSE 8000

# HEALTHCHECK: the Pi's docker/systemd supervisor uses this to decide if
# the container is alive. Uses Python (already in the image) instead of
# curl so we don't pay for extra apt packages. 30s interval, 5s timeout,
# 3 consecutive failures before the container is marked unhealthy.
# compose.yaml does not repeat this block so one definition covers
# `docker run` and `docker compose up`.
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD python3 -c "import sys, urllib.request; \
        sys.exit(0) if urllib.request.urlopen('http://127.0.0.1:${PLANTPAL_PORT:-8000}/healthz', timeout=3).status == 200 else sys.exit(1)"

# --no-server-header matches run.sh; see app/security.py for rationale.
CMD ["sh", "-c", "exec python3 -m uvicorn app.main:app --host \"${PLANTPAL_HOST}\" --port \"${PLANTPAL_PORT}\" --no-server-header"]
