"""
Plant library: name, watering display, light, description, environment.
Used to seed care_template. default_drying_days drives the engine; moisture_preference for watering style.
"""

# (name, watering_frequency_display, light_display, description, default_drying_days, moisture_preference, environment)
# moisture: dry_between, evenly_moist, moist_often. environment: indoor | outdoor
INDOOR_LIBRARY = [
    (
        "Snake Plant",
        "Every 2–4 weeks",
        "Low–Bright Indirect",
        "Let soil dry completely",
        21,
        "dry_between",
        "indoor",
    ),
    ("ZZ Plant", "Every 2–3 weeks", "Low–Medium", "Drought tolerant", 17, "dry_between", "indoor"),
    (
        "Pothos",
        "Every 1–2 weeks",
        "Low–Bright Indirect",
        'Let top 1" dry',
        10,
        "evenly_moist",
        "indoor",
    ),
    (
        "Monstera Deliciosa",
        "Every 1–2 weeks",
        "Bright Indirect",
        "Avoid soggy soil",
        10,
        "evenly_moist",
        "indoor",
    ),
    (
        "Fiddle Leaf Fig",
        'When top 1–2" dry',
        "Bright indirect · Some morning sun OK",
        "Don't let sit in water; rotate weekly for even growth",
        7,
        "dry_between",
        "indoor",
    ),
    (
        "Rubber Plant",
        "Weekly",
        "Bright Indirect",
        "Allow top soil to dry",
        7,
        "dry_between",
        "indoor",
    ),
    ("Peace Lily", "Weekly", "Low–Medium", "Droops when thirsty", 7, "evenly_moist", "indoor"),
    (
        "Spider Plant",
        "Weekly",
        "Bright Indirect",
        "Likes moderate moisture",
        7,
        "evenly_moist",
        "indoor",
    ),
    (
        "Chinese Evergreen",
        "Every 1–2 weeks",
        "Low–Medium",
        "Avoid cold drafts",
        10,
        "evenly_moist",
        "indoor",
    ),
    (
        "Philodendron Heartleaf",
        "Weekly",
        "Low–Bright Indirect",
        "Let top layer dry",
        7,
        "evenly_moist",
        "indoor",
    ),
    (
        "Aloe Vera",
        "Every 2–3 weeks",
        "Bright Direct",
        "Succulent soil",
        17,
        "dry_between",
        "indoor",
    ),
    (
        "Jade Plant",
        "Every 2–3 weeks",
        "Bright Light",
        "Let soil dry fully",
        17,
        "dry_between",
        "indoor",
    ),
    ("Calathea", "Weekly", "Medium Indirect", "High humidity needed", 7, "moist_often", "indoor"),
    (
        "Dracaena Marginata",
        "Every 2 weeks",
        "Medium",
        "Avoid fluoride water",
        14,
        "evenly_moist",
        "indoor",
    ),
    (
        "Bird of Paradise",
        "Weekly",
        "Bright Light",
        "Needs high light to thrive",
        7,
        "evenly_moist",
        "indoor",
    ),
    (
        "Boston Fern",
        "2x weekly",
        "Medium",
        "Keep soil consistently moist",
        3,
        "moist_often",
        "indoor",
    ),
    ("Areca Palm", "Weekly", "Bright Indirect", "Likes humidity", 7, "evenly_moist", "indoor"),
    (
        "Parlor Palm",
        "Every 1–2 weeks",
        "Low–Medium",
        "Avoid overwatering",
        10,
        "evenly_moist",
        "indoor",
    ),
    ("Croton", "Weekly", "Bright Light", "Needs humidity", 7, "evenly_moist", "indoor"),
    ("Dieffenbachia", "Weekly", "Medium", "Toxic to pets", 7, "evenly_moist", "indoor"),
    ("English Ivy", "Weekly", "Bright Indirect", "Keep evenly moist", 7, "evenly_moist", "indoor"),
    ("Anthurium", "Weekly", "Bright Indirect", "Allow slight drying", 7, "evenly_moist", "indoor"),
    (
        "Hoya",
        "Every 2–3 weeks",
        "Bright Indirect",
        "Let dry between watering",
        17,
        "dry_between",
        "indoor",
    ),
    (
        "String of Pearls",
        "Every 2–3 weeks",
        "Bright Light",
        "Succulent soil",
        17,
        "dry_between",
        "indoor",
    ),
    ("Peperomia", "Every 1–2 weeks", "Medium", "Avoid soggy soil", 10, "evenly_moist", "indoor"),
    ("Prayer Plant", "Weekly", "Medium", "Needs humidity", 7, "moist_often", "indoor"),
    ("Alocasia", "Weekly", "Bright Indirect", "High humidity", 7, "evenly_moist", "indoor"),
    ("Schefflera", "Weekly", "Bright Indirect", "Prune for shape", 7, "evenly_moist", "indoor"),
    (
        "Ponytail Palm",
        "Every 3–4 weeks",
        "Bright Light",
        "Drought tolerant",
        24,
        "dry_between",
        "indoor",
    ),
    (
        "Norfolk Island Pine",
        "Weekly",
        "Bright Indirect",
        "Likes cool temps",
        7,
        "evenly_moist",
        "indoor",
    ),
    ("Cast Iron Plant", "Every 2–3 weeks", "Low", "Very hardy", 17, "dry_between", "indoor"),
    (
        "Money Tree",
        'Let top 2" dry',
        "Bright indirect · Tolerates medium",
        "Does NOT like soggy roots; leaf drop = usually overwatering",
        7,
        "evenly_moist",
        "indoor",
    ),
    ("Dumb Cane", "Weekly", "Medium", "Keep soil moist", 7, "evenly_moist", "indoor"),
    ("Maidenhair Fern", "2x weekly", "Medium", "Needs high humidity", 3, "moist_often", "indoor"),
    ("Rex Begonia", "Weekly", "Bright Indirect", "Avoid leaf wetting", 7, "evenly_moist", "indoor"),
    (
        "African Violet",
        "Weekly (bottom water)",
        "Bright Indirect",
        "Avoid wet leaves",
        7,
        "evenly_moist",
        "indoor",
    ),
    ("Kalanchoe", "Every 2–3 weeks", "Bright Light", "Succulent type", 17, "dry_between", "indoor"),
    ("Aglaonema", "Every 1–2 weeks", "Low–Medium", "Easy care", 10, "evenly_moist", "indoor"),
    (
        "Philodendron Brasil",
        "Weekly",
        "Bright Indirect",
        "Let top dry",
        7,
        "evenly_moist",
        "indoor",
    ),
    ("Satin Pothos", "Weekly", "Medium", "Avoid direct sun", 7, "evenly_moist", "indoor"),
    ("Ficus Audrey", "Weekly", "Bright Indirect", 'Let top 2" dry', 7, "dry_between", "indoor"),
    (
        "Arrowhead Plant",
        "Weekly",
        "Bright Indirect",
        "Prune regularly",
        7,
        "evenly_moist",
        "indoor",
    ),
    (
        "String of Hearts",
        "Every 2–3 weeks",
        "Bright",
        "Succulent type",
        17,
        "dry_between",
        "indoor",
    ),
    ("Tradescantia", "Weekly", "Bright Indirect", "Trim to keep full", 7, "evenly_moist", "indoor"),
    ("Majesty Palm", "Weekly", "Bright Indirect", "Needs humidity", 7, "evenly_moist", "indoor"),
    ("Elephant Ear", "Weekly", "Bright Indirect", "High water needs", 7, "evenly_moist", "indoor"),
    ("Polka Dot Plant", "Weekly", "Bright Indirect", "Keep moist", 7, "evenly_moist", "indoor"),
    ("Nerve Plant", "Weekly", "Medium", "High humidity", 7, "moist_often", "indoor"),
    (
        "Bromeliad",
        "Weekly (cup refill)",
        "Bright Indirect",
        "Water central cup",
        7,
        "evenly_moist",
        "indoor",
    ),
    (
        "Cactus (generic)",
        "Every 3–4 weeks",
        "Bright Direct",
        "Let dry fully",
        24,
        "dry_between",
        "indoor",
    ),
    (
        "Clustered Column Cactus",
        "Every 2–4 weeks (less in winter)",
        "Very bright · 4–6+ hrs direct · South/west window",
        "Golden Torch / Parodia or Cleistocactus type; cactus mix + extra perlite",
        21,
        "dry_between",
        "indoor",
    ),
    (
        "Bunny Ear Cactus",
        "Every 3–4 weeks",
        "As much direct sun as possible · South-facing ideal",
        "Opuntia microdasys · Only when bone dry",
        24,
        "dry_between",
        "indoor",
    ),
    (
        "Barrel Cactus",
        "Every 3–4 weeks",
        "Bright direct sun",
        "Ferocactus or Gymnocalycium type; let dry between",
        24,
        "dry_between",
        "indoor",
    ),
    (
        "Mammillaria Cluster Cactus",
        "When fully dry",
        "Bright light",
        "Very forgiving; let soil dry completely",
        21,
        "dry_between",
        "indoor",
    ),
    (
        "Small Column Cactus",
        "When fully dry",
        "Direct sun preferred",
        "Cereus or Trichocereus type; same cactus rule—dry fully",
        24,
        "dry_between",
        "indoor",
    ),
    (
        "Christmas Cactus",
        "Every 2 weeks",
        "Bright Indirect",
        "Slight drying",
        14,
        "dry_between",
        "indoor",
    ),
    (
        "Lipstick Plant",
        "Weekly",
        "Bright Indirect",
        "Moderate moisture",
        7,
        "evenly_moist",
        "indoor",
    ),
    ("Fittonia", "Weekly", "Medium", "Needs humidity", 7, "moist_often", "indoor"),
    ("Fatsia Japonica", "Weekly", "Medium", "Keep moist", 7, "evenly_moist", "indoor"),
    (
        "Lavender (Indoor)",
        "Every 1–2 weeks",
        "Bright Direct",
        "Good drainage",
        10,
        "dry_between",
        "indoor",
    ),
    ("Mint", "Weekly", "Bright", "Keep moist", 7, "evenly_moist", "indoor"),
    ("Basil", "2x weekly", "Bright", "Don't dry out", 3, "moist_often", "indoor"),
    ("Rosemary", "Weekly", "Bright Direct", "Let dry slightly", 7, "dry_between", "indoor"),
    ("Sage", "Weekly", "Bright", "Good drainage", 7, "dry_between", "indoor"),
    ("Thyme", "Every 1–2 weeks", "Bright", "Let dry", 10, "dry_between", "indoor"),
    ("Coleus", "Weekly", "Bright Indirect", "Keep moist", 7, "evenly_moist", "indoor"),
    ("Geranium", "Weekly", "Bright", "Let dry slightly", 7, "dry_between", "indoor"),
    ("Oxalis", "Weekly", "Bright Indirect", "Dormant season", 7, "evenly_moist", "indoor"),
    ("Clivia", "Every 2 weeks", "Medium", "Dry in winter", 14, "dry_between", "indoor"),
    (
        "Snake Plant Moonshine",
        "Every 2–4 weeks",
        "Low–Bright",
        "Dry soil",
        21,
        "dry_between",
        "indoor",
    ),
    ("ZZ Raven", "Every 2–3 weeks", "Low–Medium", "Drought tolerant", 17, "dry_between", "indoor"),
    ("Philodendron Micans", "Weekly", "Medium", "Let top dry", 7, "evenly_moist", "indoor"),
    (
        "Philodendron Xanadu",
        "Weekly",
        "Bright Indirect",
        "Moderate water",
        7,
        "evenly_moist",
        "indoor",
    ),
    ("Monstera Adansonii", "Weekly", "Bright Indirect", "Let top dry", 7, "evenly_moist", "indoor"),
    (
        "Silver Dollar Vine",
        "Every 2 weeks",
        "Bright",
        "Moderate water",
        14,
        "evenly_moist",
        "indoor",
    ),
    (
        "Baby Rubber Plant",
        "Every 1–2 weeks",
        "Medium",
        "Avoid soggy soil",
        10,
        "evenly_moist",
        "indoor",
    ),
    ("Kangaroo Fern", "Weekly", "Medium", "Needs humidity", 7, "moist_often", "indoor"),
    ("Blue Star Fern", "Weekly", "Medium", "Keep moist", 7, "evenly_moist", "indoor"),
    ("Caladium", "Weekly", "Bright Indirect", "Dormant in winter", 7, "evenly_moist", "indoor"),
    ("Ti Plant", "Weekly", "Bright", "Needs humidity", 7, "evenly_moist", "indoor"),
    ("Fiddle Leaf Fig Bambino", "Weekly", "Bright", "Let top dry", 7, "dry_between", "indoor"),
    ("Dragon Tree", "Every 2 weeks", "Medium", "Avoid overwatering", 14, "evenly_moist", "indoor"),
    ("Prayer Plant Lemon Lime", "Weekly", "Medium", "High humidity", 7, "moist_often", "indoor"),
    ("Hoya Kerrii", "Every 2–3 weeks", "Bright", "Let dry", 17, "dry_between", "indoor"),
    ("Cuban Oregano", "Weekly", "Bright", "Let dry slightly", 7, "dry_between", "indoor"),
    ("Sago Palm", "Every 2 weeks", "Bright", "Toxic", 14, "dry_between", "indoor"),
    ("Bird's Nest Fern", "Weekly", "Medium", "Keep moist", 7, "evenly_moist", "indoor"),
    ("Japanese Aralia", "Weekly", "Medium", "Moderate water", 7, "evenly_moist", "indoor"),
    (
        "Silver Philodendron",
        "Weekly",
        "Bright Indirect",
        "Let top dry",
        7,
        "evenly_moist",
        "indoor",
    ),
    ("Ficus Benjamina", "Weekly", "Bright", "Sensitive to movement", 7, "evenly_moist", "indoor"),
    ("Calathea Orbifolia", "Weekly", "Medium", "High humidity", 7, "moist_often", "indoor"),
    (
        "String of Bananas",
        "Every 2–3 weeks",
        "Bright",
        "Succulent type",
        17,
        "dry_between",
        "indoor",
    ),
    ("Panda Plant", "Every 3 weeks", "Bright", "Let dry fully", 21, "dry_between", "indoor"),
    ("Crown of Thorns", "Every 2 weeks", "Bright", "Drought tolerant", 14, "dry_between", "indoor"),
    ("Flaming Katy", "Every 2–3 weeks", "Bright", "Succulent", 17, "dry_between", "indoor"),
    (
        "Chinese Money Plant",
        "Weekly",
        "Bright Indirect",
        "Rotate often",
        7,
        "evenly_moist",
        "indoor",
    ),
    (
        "Air Plant",
        "Weekly soak",
        "Bright Indirect",
        "Dry fully after soak",
        7,
        "evenly_moist",
        "indoor",
    ),
    ("Pencil Cactus", "Every 3 weeks", "Bright", "Let dry", 21, "dry_between", "indoor"),
    ("Zebra Haworthia", "Every 2–3 weeks", "Bright", "Succulent", 17, "dry_between", "indoor"),
    ("Gasteria", "Every 2–3 weeks", "Bright", "Dry soil", 17, "dry_between", "indoor"),
    ("Echeveria", "Every 2–3 weeks", "Bright", "Succulent", 17, "dry_between", "indoor"),
    ("Burro's Tail", "Every 2–3 weeks", "Bright", "Let dry", 17, "dry_between", "indoor"),
    ("Dumb Cane Camille", "Weekly", "Medium", "Keep moist", 7, "evenly_moist", "indoor"),
    ("Agave", "Every 3–4 weeks", "Bright", "Let dry", 24, "dry_between", "indoor"),
    ("Rattlesnake Plant", "Weekly", "Medium", "Needs humidity", 7, "moist_often", "indoor"),
    # Bonsai: small pots dry quickly; schedules are starting points—adjust for species and season
    (
        "Ficus Bonsai",
        "When top soil just starts to dry",
        "Bright indirect · some direct OK",
        "Fast-draining bonsai mix; protect from cold drafts",
        7,
        "evenly_moist",
        "indoor",
    ),
    (
        "Juniper Bonsai",
        "Often (small pot dries fast)",
        "Very bright · ideally outdoors part-time",
        "Likes humidity; many do best outside spring–fall",
        5,
        "evenly_moist",
        "indoor",
    ),
    (
        "Japanese Maple Bonsai",
        "Frequently · never bone dry",
        "Bright indirect · avoid harsh midday sun",
        "Keep evenly moist; sensitive to drying out",
        5,
        "evenly_moist",
        "indoor",
    ),
    (
        "Jade Bonsai",
        "Every 2–3 weeks",
        "Bright direct to indirect",
        "Succulent; let soil dry between waterings",
        14,
        "dry_between",
        "indoor",
    ),
    (
        "Pine Bonsai",
        "When top layer dries slightly",
        "Full sun to very bright",
        "Well-draining mix; reduce water in winter dormancy",
        7,
        "evenly_moist",
        "indoor",
    ),
    (
        "Indoor Bonsai (general)",
        "When surface begins to dry",
        "Bright indirect",
        "Shallow pot = check often; species vary—observe your tree",
        7,
        "evenly_moist",
        "indoor",
    ),
]

# Outdoor plants: (name, watering, light, description with zone, days, moisture, "outdoor")
OUTDOOR_LIBRARY = [
    (
        "Black-Eyed Susan",
        "Weekly (until established)",
        "Full Sun",
        "Zone 3–9 · Drought tolerant once established",
        7,
        "dry_between",
        "outdoor",
    ),
    (
        "Coneflower (Echinacea)",
        "Weekly",
        "Full Sun",
        "Zone 3–9 · Pollinator friendly",
        7,
        "dry_between",
        "outdoor",
    ),
    ("Daylily", "Weekly", "Full Sun", "Zone 3–10 · Very hardy", 7, "evenly_moist", "outdoor"),
    (
        "Shasta Daisy",
        "Weekly",
        "Full Sun",
        "Zone 5–9 · Deadhead blooms",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Peony", "Weekly", "Full Sun", "Zone 3–8 · Needs cold winter", 7, "evenly_moist", "outdoor"),
    (
        "Lavender",
        "Every 1–2 weeks",
        "Full Sun",
        "Zone 5–9 · Excellent drainage required",
        10,
        "dry_between",
        "outdoor",
    ),
    ("Coreopsis", "Weekly", "Full Sun", "Zone 4–9 · Drought tolerant", 7, "dry_between", "outdoor"),
    (
        "Salvia",
        "Weekly",
        "Full Sun",
        "Zone 4–10 · Attracts pollinators",
        7,
        "dry_between",
        "outdoor",
    ),
    (
        "Yarrow",
        "Every 1–2 weeks",
        "Full Sun",
        "Zone 3–9 · Very drought tolerant",
        10,
        "dry_between",
        "outdoor",
    ),
    (
        "Bee Balm",
        "Weekly",
        "Full Sun–Part Sun",
        "Zone 3–9 · Spreads aggressively",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Hostas", "Weekly", "Shade", "Zone 3–9 · Avoid harsh sun", 7, "evenly_moist", "outdoor"),
    ("Astilbe", "Weekly", "Part Shade", "Zone 4–9 · Likes moisture", 7, "moist_often", "outdoor"),
    ("Columbine", "Weekly", "Part Sun", "Zone 3–8 · Self-seeds", 7, "evenly_moist", "outdoor"),
    (
        "Phlox",
        "Weekly",
        "Full Sun",
        "Zone 4–8 · Needs air circulation",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Sedum",
        "Every 2–3 weeks",
        "Full Sun",
        "Zone 3–9 · Succulent type",
        17,
        "dry_between",
        "outdoor",
    ),
    (
        "Boxwood",
        "Weekly (new)",
        "Full Sun–Part Shade",
        "Zone 5–9 · Prune for shape",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Hydrangea (Bigleaf)",
        "Weekly",
        "Part Sun",
        "Zone 5–9 · Soil affects bloom color",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Hydrangea (Panicle)",
        "Weekly",
        "Full Sun",
        "Zone 3–8 · Hardy type",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Azalea", "Weekly", "Part Shade", "Zone 6–9 · Acidic soil", 7, "evenly_moist", "outdoor"),
    (
        "Rhododendron",
        "Weekly",
        "Part Shade",
        "Zone 4–8 · Avoid afternoon sun",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Rose (Knock Out)",
        "Weekly",
        "Full Sun",
        "Zone 5–10 · Deadhead regularly",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Lilac", "Weekly", "Full Sun", "Zone 3–7 · Needs winter chill", 7, "evenly_moist", "outdoor"),
    (
        "Forsythia",
        "Weekly",
        "Full Sun",
        "Zone 5–8 · Early spring bloomer",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Butterfly Bush",
        "Weekly",
        "Full Sun",
        "Zone 5–9 · Cut back in spring",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Holly",
        "Weekly",
        "Full Sun–Part Shade",
        "Zone 5–9 · Some need male/female",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Red Maple",
        "Weekly (young)",
        "Full Sun",
        "Zone 3–9 · Adaptable",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Dogwood",
        "Weekly",
        "Part Sun",
        "Zone 5–9 · Avoid drought stress",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Eastern Redbud",
        "Weekly",
        "Full Sun",
        "Zone 4–9 · Early spring flowers",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Magnolia", "Weekly", "Full Sun", "Zone 5–9 · Needs space", 7, "evenly_moist", "outdoor"),
    (
        "Crepe Myrtle",
        "Weekly",
        "Full Sun",
        "Zone 6–10 · Drought tolerant",
        7,
        "dry_between",
        "outdoor",
    ),
    (
        "Arborvitae",
        "Weekly",
        "Full Sun",
        "Zone 3–8 · Consistent watering when young",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Japanese Maple",
        "Weekly",
        "Part Shade",
        "Zone 5–8 · Avoid hot sun",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Oak Tree",
        "Weekly (young)",
        "Full Sun",
        "Zone 3–9 · Deep roots",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Birch", "Weekly", "Full Sun", "Zone 2–7 · Needs moisture", 7, "moist_often", "outdoor"),
    (
        "Pine (Landscape)",
        "Every 2 weeks",
        "Full Sun",
        "Zone 3–8 · Low maintenance",
        14,
        "dry_between",
        "outdoor",
    ),
    (
        "Fountain Grass",
        "Weekly",
        "Full Sun",
        "Zone 5–9 · Cut back annually",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Maiden Grass",
        "Weekly",
        "Full Sun",
        "Zone 5–9 · Tall ornamental",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Blue Fescue",
        "Every 2 weeks",
        "Full Sun",
        "Zone 4–8 · Compact",
        14,
        "dry_between",
        "outdoor",
    ),
    (
        "Switchgrass",
        "Weekly",
        "Full Sun",
        "Zone 4–9 · Native prairie",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Muhly Grass",
        "Weekly",
        "Full Sun",
        "Zone 6–10 · Pink fall plumes",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Petunia", "2–3x weekly", "Full Sun", "Annual · Deadhead", 4, "evenly_moist", "outdoor"),
    ("Marigold", "Weekly", "Full Sun", "Annual · Drought tolerant", 7, "dry_between", "outdoor"),
    ("Zinnia", "Weekly", "Full Sun", "Annual · Attracts butterflies", 7, "evenly_moist", "outdoor"),
    ("Impatiens", "2–3x weekly", "Shade", "Annual · Keep moist", 4, "moist_often", "outdoor"),
    (
        "Begonia (outdoor)",
        "Weekly",
        "Part Shade",
        "Annual · Avoid overwatering",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Tomato", "2–3x weekly", "Full Sun", "Annual · Deep watering", 4, "moist_often", "outdoor"),
    ("Pepper", "2x weekly", "Full Sun", "Annual · Warm soil", 3, "evenly_moist", "outdoor"),
    ("Cucumber", "2–3x weekly", "Full Sun", "Annual · Needs support", 4, "moist_often", "outdoor"),
    ("Lettuce", "2–3x weekly", "Part Sun", "Annual · Cool season", 4, "moist_often", "outdoor"),
    ("Carrot", "Weekly", "Full Sun", "Annual · Loose soil", 7, "evenly_moist", "outdoor"),
    ("Blueberry", "Weekly", "Full Sun", "Zone 3–8 · Acidic soil", 7, "evenly_moist", "outdoor"),
    ("Strawberry", "Weekly", "Full Sun", "Zone 4–8 · Mulch helps", 7, "evenly_moist", "outdoor"),
    ("Raspberry", "Weekly", "Full Sun", "Zone 4–8 · Prune annually", 7, "evenly_moist", "outdoor"),
    (
        "Apple Tree",
        "Weekly (young)",
        "Full Sun",
        "Zone 3–8 · Needs pollinator",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Peach Tree", "Weekly", "Full Sun", "Zone 5–8 · Prune yearly", 7, "evenly_moist", "outdoor"),
    (
        "Agave",
        "Every 3–4 weeks",
        "Full Sun",
        "Zone 8–11 · Very drought tolerant",
        24,
        "dry_between",
        "outdoor",
    ),
    (
        "Yucca",
        "Every 2–3 weeks",
        "Full Sun",
        "Zone 4–10 · Sharp leaves",
        17,
        "dry_between",
        "outdoor",
    ),
    (
        "Russian Sage",
        "Every 2 weeks",
        "Full Sun",
        "Zone 4–9 · Drought tolerant",
        14,
        "dry_between",
        "outdoor",
    ),
    (
        "Ice Plant",
        "Every 2 weeks",
        "Full Sun",
        "Zone 5–9 · Succulent",
        14,
        "dry_between",
        "outdoor",
    ),
    (
        "Prickly Pear",
        "Every 3–4 weeks",
        "Full Sun",
        "Zone 4–9 · Cactus",
        24,
        "dry_between",
        "outdoor",
    ),
    (
        "Creeping Jenny",
        "Weekly",
        "Full Sun–Part Shade",
        "Zone 3–9 · Spreads fast",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Vinca", "Weekly", "Shade", "Zone 4–9 · Evergreen", 7, "evenly_moist", "outdoor"),
    ("Ajuga", "Weekly", "Part Shade", "Zone 3–9 · Good filler", 7, "evenly_moist", "outdoor"),
    ("Sweet Woodruff", "Weekly", "Shade", "Zone 4–8 · Fragrant", 7, "evenly_moist", "outdoor"),
    (
        "Creeping Thyme",
        "Every 1–2 weeks",
        "Full Sun",
        "Zone 4–9 · Drought tolerant",
        10,
        "dry_between",
        "outdoor",
    ),
    ("Camellia", "Weekly", "Part Shade", "Zone 7–9 · Winter bloomer", 7, "evenly_moist", "outdoor"),
    (
        "Gardenia",
        "Weekly",
        "Full Sun–Part Shade",
        "Zone 7–10 · Needs acidity",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Oleander", "Weekly", "Full Sun", "Zone 8–11 · Toxic", 7, "evenly_moist", "outdoor"),
    ("Hibiscus", "2x weekly", "Full Sun", "Zone 9–11 · Tropical", 3, "moist_often", "outdoor"),
    ("Lantana", "Weekly", "Full Sun", "Zone 8–11 · Heat tolerant", 7, "dry_between", "outdoor"),
    (
        "Tulip",
        "Weekly (spring)",
        "Full Sun",
        "Zone 3–8 · Needs winter chill",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Daffodil", "Weekly", "Full Sun", "Zone 3–8 · Deer resistant", 7, "evenly_moist", "outdoor"),
    ("Allium", "Weekly", "Full Sun", "Zone 4–8 · Decorative blooms", 7, "evenly_moist", "outdoor"),
    (
        "Gladiolus",
        "Weekly",
        "Full Sun",
        "Zone 7–10 · Lift in cold climates",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Crocus", "Weekly", "Full Sun", "Zone 3–8 · Early bloom", 7, "evenly_moist", "outdoor"),
    ("Milkweed", "Weekly", "Full Sun", "Zone 3–9 · Monarch host", 7, "evenly_moist", "outdoor"),
    (
        "Blazing Star",
        "Weekly",
        "Full Sun",
        "Zone 3–9 · Native prairie",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Goldenrod", "Weekly", "Full Sun", "Zone 2–8 · Fall blooms", 7, "evenly_moist", "outdoor"),
    ("Joe Pye Weed", "Weekly", "Full Sun", "Zone 4–9 · Moist soil", 7, "moist_often", "outdoor"),
    ("Wild Bergamot", "Weekly", "Full Sun", "Zone 3–9 · Spreads", 7, "evenly_moist", "outdoor"),
    (
        "Juniper",
        "Every 2 weeks",
        "Full Sun",
        "Zone 3–9 · Drought tolerant",
        14,
        "dry_between",
        "outdoor",
    ),
    ("Spruce", "Weekly (young)", "Full Sun", "Zone 2–7 · Cold hardy", 7, "evenly_moist", "outdoor"),
    ("Cedar", "Weekly", "Full Sun", "Zone 2–8 · Wind resistant", 7, "evenly_moist", "outdoor"),
    (
        "Leyland Cypress",
        "Weekly",
        "Full Sun",
        "Zone 6–10 · Fast growing",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Privet", "Weekly", "Full Sun", "Zone 5–9 · Hedge plant", 7, "evenly_moist", "outdoor"),
    ("Clematis", "Weekly", "Full Sun", "Zone 4–9 · Cool roots", 7, "evenly_moist", "outdoor"),
    ("Wisteria", "Weekly", "Full Sun", "Zone 5–9 · Aggressive", 7, "evenly_moist", "outdoor"),
    (
        "Climbing Rose",
        "Weekly",
        "Full Sun",
        "Zone 5–9 · Support structure",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Trumpet Vine",
        "Weekly",
        "Full Sun",
        "Zone 4–9 · Spreads aggressively",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Honeysuckle",
        "Weekly",
        "Full Sun",
        "Zone 4–9 · Attracts hummingbirds",
        7,
        "evenly_moist",
        "outdoor",
    ),
    (
        "Geranium (Perennial)",
        "Weekly",
        "Full Sun",
        "Zone 4–8 · Easy care",
        7,
        "dry_between",
        "outdoor",
    ),
    ("Snapdragons", "Weekly", "Full Sun", "Annual · Cool season", 7, "evenly_moist", "outdoor"),
    (
        "Pansy",
        "Weekly",
        "Full Sun–Part Shade",
        "Annual · Cool weather",
        7,
        "evenly_moist",
        "outdoor",
    ),
    ("Cosmos", "Weekly", "Full Sun", "Annual · Self-seeds", 7, "evenly_moist", "outdoor"),
    ("Sunflower", "Weekly", "Full Sun", "Annual · Tall grower", 7, "evenly_moist", "outdoor"),
    ("Morning Glory", "Weekly", "Full Sun", "Annual · Climber", 7, "evenly_moist", "outdoor"),
    ("Dusty Miller", "Weekly", "Full Sun", "Annual · Silvery foliage", 7, "dry_between", "outdoor"),
    ("Foxglove", "Weekly", "Part Shade", "Zone 4–9 · Biennial", 7, "evenly_moist", "outdoor"),
    ("Gaillardia", "Weekly", "Full Sun", "Zone 3–10 · Heat tolerant", 7, "dry_between", "outdoor"),
    ("Veronica", "Weekly", "Full Sun", "Zone 4–8 · Compact blooms", 7, "evenly_moist", "outdoor"),
]

PLANT_LIBRARY = INDOOR_LIBRARY + OUTDOOR_LIBRARY


def slug_from_name(name: str) -> str:
    """Generate URL-safe slug from plant name (no user input in SQL)."""
    return (
        name.lower()
        .replace(" ", "-")
        .replace("'", "")
        .replace("(", "")
        .replace(")", "")
        .replace("/", "-")
        .replace("–", "-")[:80]
    )


# --- Categories for grouping in library (indoor vs outdoor) ---
# Indoor: Foliage (default), Succulents & Cacti, Ferns, Flowering Houseplants, Palms, Bonsai, Herbs & Spices, Trailing & Vines, Easy Care
INDOOR_CATEGORIES = {
    "snake-plant": "Easy Care",
    "zz-plant": "Easy Care",
    "pothos": "Trailing & Vines",
    "monstera-deliciosa": "Foliage",
    "fiddle-leaf-fig": "Foliage",
    "rubber-plant": "Foliage",
    "peace-lily": "Flowering Houseplants",
    "spider-plant": "Trailing & Vines",
    "chinese-evergreen": "Easy Care",
    "philodendron-heartleaf": "Trailing & Vines",
    "aloe-vera": "Succulents & Cacti",
    "jade-plant": "Succulents & Cacti",
    "calathea": "Foliage",
    "dracaena-marginata": "Foliage",
    "bird-of-paradise": "Foliage",
    "boston-fern": "Ferns",
    "areca-palm": "Palms",
    "parlor-palm": "Palms",
    "croton": "Foliage",
    "dieffenbachia": "Foliage",
    "english-ivy": "Trailing & Vines",
    "anthurium": "Flowering Houseplants",
    "hoya": "Trailing & Vines",
    "string-of-pearls": "Succulents & Cacti",
    "peperomia": "Foliage",
    "prayer-plant": "Foliage",
    "alocasia": "Foliage",
    "schefflera": "Foliage",
    "ponytail-palm": "Palms",
    "norfolk-island-pine": "Foliage",
    "cast-iron-plant": "Easy Care",
    "money-tree": "Foliage",
    "dumb-cane": "Foliage",
    "maidenhair-fern": "Ferns",
    "rex-begonia": "Begonias & Rex",
    "african-violet": "Flowering Houseplants",
    "kalanchoe": "Succulents & Cacti",
    "aglaonema": "Easy Care",
    "philodendron-brasil": "Trailing & Vines",
    "satin-pothos": "Trailing & Vines",
    "ficus-audrey": "Foliage",
    "arrowhead-plant": "Trailing & Vines",
    "string-of-hearts": "Succulents & Cacti",
    "tradescantia": "Trailing & Vines",
    "majesty-palm": "Palms",
    "elephant-ear": "Foliage",
    "polka-dot-plant": "Foliage",
    "nerve-plant": "Foliage",
    "bromeliad": "Flowering Houseplants",
    "cactus-generic": "Succulents & Cacti",
    "clustered-column-cactus": "Succulents & Cacti",
    "bunny-ear-cactus": "Succulents & Cacti",
    "barrel-cactus": "Succulents & Cacti",
    "mammillaria-cluster-cactus": "Succulents & Cacti",
    "small-column-cactus": "Succulents & Cacti",
    "christmas-cactus": "Succulents & Cacti",
    "lipstick-plant": "Flowering Houseplants",
    "fittonia": "Foliage",
    "fatsia-japonica": "Foliage",
    "lavender-indoor": "Herbs & Spices",
    "mint": "Herbs & Spices",
    "basil": "Herbs & Spices",
    "rosemary": "Herbs & Spices",
    "sage": "Herbs & Spices",
    "thyme": "Herbs & Spices",
    "coleus": "Foliage",
    "geranium": "Flowering Houseplants",
    "oxalis": "Foliage",
    "clivia": "Flowering Houseplants",
    "snake-plant-moonshine": "Easy Care",
    "zz-raven": "Easy Care",
    "philodendron-micans": "Trailing & Vines",
    "philodendron-xanadu": "Foliage",
    "monstera-adansonii": "Trailing & Vines",
    "silver-dollar-vine": "Trailing & Vines",
    "baby-rubber-plant": "Foliage",
    "kangaroo-fern": "Ferns",
    "blue-star-fern": "Ferns",
    "caladium": "Foliage",
    "ti-plant": "Foliage",
    "fiddle-leaf-fig-bambino": "Foliage",
    "dragon-tree": "Foliage",
    "prayer-plant-lemon-lime": "Foliage",
    "hoya-kerrii": "Trailing & Vines",
    "cuban-oregano": "Herbs & Spices",
    "sago-palm": "Palms",
    "birds-nest-fern": "Ferns",
    "japanese-aralia": "Foliage",
    "silver-philodendron": "Trailing & Vines",
    "ficus-benjamina": "Foliage",
    "calathea-orbifolia": "Foliage",
    "string-of-bananas": "Succulents & Cacti",
    "panda-plant": "Succulents & Cacti",
    "crown-of-thorns": "Succulents & Cacti",
    "flaming-katy": "Succulents & Cacti",
    "chinese-money-plant": "Foliage",
    "air-plant": "Flowering Houseplants",
    "pencil-cactus": "Succulents & Cacti",
    "zebra-haworthia": "Succulents & Cacti",
    "gasteria": "Succulents & Cacti",
    "echeveria": "Succulents & Cacti",
    "burros-tail": "Succulents & Cacti",
    "dumb-cane-camille": "Foliage",
    "agave": "Succulents & Cacti",
    "rattlesnake-plant": "Foliage",
    "ficus-bonsai": "Bonsai",
    "juniper-bonsai": "Bonsai",
    "japanese-maple-bonsai": "Bonsai",
    "jade-bonsai": "Bonsai",
    "pine-bonsai": "Bonsai",
    "indoor-bonsai-general": "Bonsai",
}
# Outdoor categories
OUTDOOR_CATEGORIES = {
    "black-eyed-susan": "Flowering Perennials",
    "coneflower-echinacea": "Flowering Perennials",
    "daylily": "Flowering Perennials",
    "shasta-daisy": "Flowering Perennials",
    "peony": "Flowering Perennials",
    "lavender": "Herbs & Spices",
    "coreopsis": "Flowering Perennials",
    "salvia": "Flowering Perennials",
    "yarrow": "Flowering Perennials",
    "bee-balm": "Flowering Perennials",
    "hostas": "Flowering Perennials",
    "astilbe": "Flowering Perennials",
    "columbine": "Flowering Perennials",
    "phlox": "Flowering Perennials",
    "sedum": "Flowering Perennials",
    "boxwood": "Shrubs",
    "hydrangea-bigleaf": "Shrubs",
    "hydrangea-panicle": "Shrubs",
    "azalea": "Shrubs",
    "rhododendron": "Shrubs",
    "rose-knock-out": "Shrubs",
    "lilac": "Shrubs",
    "forsythia": "Shrubs",
    "butterfly-bush": "Shrubs",
    "holly": "Shrubs",
    "red-maple": "Trees",
    "dogwood": "Trees",
    "eastern-redbud": "Trees",
    "magnolia": "Trees",
    "crepe-myrtle": "Trees",
    "arborvitae": "Trees",
    "japanese-maple": "Trees",
    "oak-tree": "Trees",
    "birch": "Trees",
    "pine-landscape": "Trees",
    "fountain-grass": "Ornamental Grasses",
    "maiden-grass": "Ornamental Grasses",
    "blue-fescue": "Ornamental Grasses",
    "switchgrass": "Ornamental Grasses",
    "muhly-grass": "Ornamental Grasses",
    "petunia": "Annuals",
    "marigold": "Annuals",
    "zinnia": "Annuals",
    "impatiens": "Annuals",
    "begonia-outdoor": "Annuals",
    "tomato": "Fruits & Vegetables",
    "pepper": "Fruits & Vegetables",
    "cucumber": "Fruits & Vegetables",
    "lettuce": "Fruits & Vegetables",
    "carrot": "Fruits & Vegetables",
    "blueberry": "Fruits & Vegetables",
    "strawberry": "Fruits & Vegetables",
    "raspberry": "Fruits & Vegetables",
    "apple-tree": "Fruits & Vegetables",
    "peach-tree": "Fruits & Vegetables",
    "agave": "Drought / Xeriscape",
    "yucca": "Drought / Xeriscape",
    "russian-sage": "Drought / Xeriscape",
    "ice-plant": "Drought / Xeriscape",
    "prickly-pear": "Drought / Xeriscape",
    "creeping-jenny": "Groundcovers",
    "vinca": "Groundcovers",
    "ajuga": "Groundcovers",
    "sweet-woodruff": "Groundcovers",
    "creeping-thyme": "Herbs & Spices",
    "camellia": "Southern Favorites",
    "gardenia": "Southern Favorites",
    "oleander": "Southern Favorites",
    "hibiscus": "Southern Favorites",
    "lantana": "Southern Favorites",
    "tulip": "Bulbs",
    "daffodil": "Bulbs",
    "allium": "Bulbs",
    "gladiolus": "Bulbs",
    "crocus": "Bulbs",
    "milkweed": "Native / Low Maintenance",
    "blazing-star": "Native / Low Maintenance",
    "goldenrod": "Native / Low Maintenance",
    "joe-pye-weed": "Native / Low Maintenance",
    "wild-bergamot": "Native / Low Maintenance",
    "juniper": "Evergreen Shrubs / Trees",
    "spruce": "Evergreen Shrubs / Trees",
    "cedar": "Evergreen Shrubs / Trees",
    "leyland-cypress": "Evergreen Shrubs / Trees",
    "privet": "Evergreen Shrubs / Trees",
    "clematis": "Climbing Plants",
    "wisteria": "Climbing Plants",
    "climbing-rose": "Climbing Plants",
    "trumpet-vine": "Climbing Plants",
    "honeysuckle": "Climbing Plants",
    "geranium-perennial": "Flowering Perennials",
    "snapdragons": "Annuals",
    "pansy": "Annuals",
    "cosmos": "Annuals",
    "sunflower": "Annuals",
    "morning-glory": "Annuals",
    "dusty-miller": "Annuals",
    "foxglove": "Flowering Perennials",
    "gaillardia": "Flowering Perennials",
    "veronica": "Flowering Perennials",
}

# Default growing/care line when no specific instructions (by category)
DEFAULT_GROWING_BY_CATEGORY = {
    "Foliage": "Place in indirect light; water when the top inch of soil is dry. Wipe leaves occasionally and rotate for even growth.",
    "Easy Care": "Tolerates low light and irregular watering. Let soil dry between waterings; avoid overwatering.",
    "Trailing & Vines": "Provide bright indirect light and support or hanging space. Pinch back to encourage bushiness.",
    "Succulents & Cacti": "Bright light and excellent drainage. Water only when soil is fully dry; reduce in winter.",
    "Ferns": "Keep soil consistently moist and provide humidity (mist or pebble tray). Avoid direct sun and drafts.",
    "Palms": "Bright indirect light; keep soil evenly moist. Brown tips often mean dry air or fluoride in water—use filtered if needed.",
    "Flowering Houseplants": "Bright indirect light; keep moist during bloom. Remove spent flowers; some need a rest period after blooming.",
    "Herbs & Spices": "Bright light; well-draining soil. Harvest regularly to encourage growth; use fresh or dry for cooking.",
    "Fruits & Vegetables": "Full sun outdoors or brightest spot indoors. Consistent water and feed when fruiting; support vines as needed.",
    "Begonias & Rex": "Bright indirect light; avoid wet leaves. Water when top layer is dry; high humidity helps.",
    "Flowering Perennials": "Site according to light needs; water until established. Deadhead and divide as recommended for the variety.",
    "Shrubs": "Plant in correct zone; water regularly when young. Prune after flowering or in late winter as appropriate.",
    "Trees": "Full sun to part shade per species. Water deeply when young; mulch to retain moisture.",
    "Ornamental Grasses": "Full sun; well-drained soil. Cut back in late winter before new growth.",
    "Annuals": "Full sun or part shade per type. Keep moist; deadhead for continuous bloom.",
    "Bulbs": "Plant at correct depth; water after planting. Allow foliage to die back after flowering before cutting.",
    "Drought / Xeriscape": "Full sun; excellent drainage. Water sparingly once established.",
    "Groundcovers": "Match light to variety; water until established. Trim to control spread.",
    "Southern Favorites": "Warm, sheltered spot; protect from frost. Water and feed as per variety.",
    "Native / Low Maintenance": "Match to your zone and site. Water until established; then minimal care.",
    "Evergreen Shrubs / Trees": "Site for sun and space. Water when young; little pruning needed once shaped.",
    "Climbing Plants": "Support structure; full sun or part shade. Prune after flowering as needed.",
    "Ornamental": "Provide light and water as described for the plant; adjust for your conditions.",
    "Other": "Water and light as described. Adjust for your home or garden conditions.",
    "Bonsai": "Use fast-draining bonsai soil and a pot with drainage. Water when the top layer matches your species (often nearly dry for conifers, slightly moist for maples). Fertilize lightly in growing season; repot on a species-appropriate schedule.",
}

# Growing / care instructions (searchable); specific entries override category defaults
GROWING_INSTRUCTIONS = {
    (
        "fiddle-leaf-fig",
        "indoor",
    ): "Bright indirect light; some morning sun OK. Avoid harsh afternoon sun. Water when top 1–2 inches of soil are dry. Don't let it sit in water. Rotate weekly for even growth.",
    (
        "money-tree",
        "indoor",
    ): "Bright indirect light; tolerates medium light. Let top 2 inches of soil dry between waterings. Does NOT like soggy roots. Watch for leaf drop—usually means overwatering.",
    (
        "clustered-column-cactus",
        "indoor",
    ): "Very bright light; 4–6+ hours direct sun preferred. South or west window indoors. Let soil dry completely; water every 2–4 weeks (less in winter). Use cactus mix + extra perlite; must drain fast. If it starts stretching taller and thinner, it needs more light. (Likely Golden Torch / Parodia or Cleistocactus type.)",
    (
        "bunny-ear-cactus",
        "indoor",
    ): "As much direct sun as possible; south-facing window is ideal. Water only when bone dry—about every 3–4 weeks indoors. Warning: those tiny dots are glochids; they stick like fiberglass. Avoid touching. Skinny upward growth suggests it may want more light. (Opuntia microdasys.)",
    (
        "barrel-cactus",
        "indoor",
    ): "Bright direct sun. Water every 3–4 weeks; let soil dry completely between waterings. (Ferocactus or Gymnocalycium type.)",
    (
        "mammillaria-cluster-cactus",
        "indoor",
    ): "Bright light. Let soil dry fully between waterings. Very forgiving.",
    (
        "small-column-cactus",
        "indoor",
    ): "Direct sun preferred. Same cactus rule—let soil dry fully before watering. (Possibly Cereus or Trichocereus juvenile.)",
    (
        "basil",
        "indoor",
    ): "Start from seed or cuttings in a sunny window. Pinch tips regularly to encourage bushiness and prevent flowering. Harvest leaves from the top; keep soil moist. Use in pesto, caprese, and pasta.",
    (
        "mint",
        "indoor",
    ): "Grow in a pot (it spreads). Bright light, keep soil moist. Harvest by snipping stems. Use in tea, cocktails, and lamb. Can grow from cuttings in water.",
    (
        "rosemary",
        "indoor",
    ): "Needs bright light and good drainage. Let soil dry slightly between waterings. Trim to shape. Use with roasted meats, potatoes, and bread.",
    (
        "sage",
        "indoor",
    ): "Bright light, well-draining soil. Water when top inch is dry. Harvest leaves as needed. Use in stuffing, brown butter, and pasta.",
    (
        "thyme",
        "indoor",
    ): "Bright light, let soil dry between waterings. Trim after flowering. Use in soups, roast chicken, and vegetables.",
    (
        "lavender-indoor",
        "indoor",
    ): "Bright direct light, excellent drainage. Water when dry. Harvest flowers when just open. Use for sachets, baking, and tea.",
    (
        "cuban-oregano",
        "indoor",
    ): "Bright light, let soil dry slightly. Strong flavor for beans, meats, and sofrito.",
    (
        "lavender",
        "outdoor",
    ): "Full sun, very well-drained soil. Prune after flowering. Drought tolerant once established. Harvest flowers for drying or culinary use.",
    (
        "creeping-thyme",
        "outdoor",
    ): "Full sun, well-drained soil. Drought tolerant. Use leaves in cooking; also a fragrant groundcover.",
    (
        "tomato",
        "outdoor",
    ): "Full sun, deep watering 2–3x per week. Stake or cage. Feed when flowering. Harvest when fully colored. Start from transplants or seed indoors 6–8 weeks before last frost.",
    (
        "pepper",
        "outdoor",
    ): "Full sun, warm soil. Water 2x weekly; consistent moisture for best fruit. Harvest when firm and colored. Sweet and hot types.",
    (
        "cucumber",
        "outdoor",
    ): "Full sun, trellis or support. Keep soil moist. Harvest when firm and before yellowing. Great for salads and pickling.",
    (
        "lettuce",
        "outdoor",
    ): "Part sun, cool season. Keep moist; water 2–3x weekly. Harvest outer leaves or whole head. Plant in spring or fall.",
    (
        "carrot",
        "outdoor",
    ): "Full sun, loose deep soil. Thin seedlings. Water weekly. Harvest when shoulders are visible; store in cool place.",
    (
        "blueberry",
        "outdoor",
    ): "Full sun, acidic soil (pH 4.5–5.5). Mulch. Water weekly. Prune in late winter. Harvest when fully blue.",
    (
        "strawberry",
        "outdoor",
    ): "Full sun, well-drained soil. Mulch under fruit. Water regularly. Remove runners if not propagating. June-bearing or everbearing.",
    (
        "raspberry",
        "outdoor",
    ): "Full sun. Prune canes annually (summer vs fall bearing). Water weekly. Harvest when they slip off.",
    (
        "apple-tree",
        "outdoor",
    ): "Full sun, well-drained soil. Needs pollinator variety. Prune in late winter. Water young trees weekly. Thin fruit for size.",
    (
        "peach-tree",
        "outdoor",
    ): "Full sun. Prune yearly for open center. Water when dry. Harvest when fruit gives slightly and is fragrant.",
    (
        "ficus-bonsai",
        "indoor",
    ): "Bright indirect light; some morning sun is fine. Water when the top ½ inch begins to dry—never let it sit soggy. Prune and wire during active growth; protect from cold drafts.",
    (
        "juniper-bonsai",
        "indoor",
    ): "Needs strong light; many junipers struggle indoors long-term—outdoor part-time or a very bright spot helps. Keep soil slightly moist (not wet); misting or humidity tray in dry air.",
    (
        "japanese-maple-bonsai",
        "indoor",
    ): "Never let the rootball dry completely. Bright indirect light; avoid scorching midday sun. Protect from drying heat vents; maples prefer cool roots.",
    (
        "jade-bonsai",
        "indoor",
    ): "Treat like a succulent: full dry between waterings, excellent drainage. Bright light for compact growth; ease up on water in winter.",
    (
        "pine-bonsai",
        "indoor",
    ): "Very bright light; many pines want a winter cool period if possible. Water thoroughly when top soil dries a bit; reduce frequency in winter.",
    (
        "indoor-bonsai-general",
        "indoor",
    ): "Shallow pots dry quickly—check often. Match watering to species (deciduous vs conifer vs tropical). Repot before soil breaks down; wire and prune during the right season for your tree.",
}


def get_category_and_growing(slug: str, env: str) -> tuple:
    """Return (category, growing_instructions) for a template. Used by seed/backfill."""
    if env == "indoor":
        cat = INDOOR_CATEGORIES.get(slug, "Foliage")
    else:
        cat = OUTDOOR_CATEGORIES.get(slug, "Ornamental")
    growing = GROWING_INSTRUCTIONS.get((slug, env), "") or DEFAULT_GROWING_BY_CATEGORY.get(
        cat, "Water and light as described. Adjust for your conditions."
    )
    return (cat, growing)


def get_icon_id(slug: str, env: str) -> str:
    """Return icon_id for this plant slug. Each slug gets a stable icon (slug is used as icon_id; icons.py maps to a unique graphic)."""
    return slug
