"""
Maps library (slug, environment) → visual_type for care_template seeding and sync.
Explicit entries follow product archetypes; anything else uses a simple indoor/outdoor default.
"""

from __future__ import annotations

# (slug, "indoor"|"outdoor") → visual_type (matches /static/plants/{type}.png)
VISUAL_TYPE_BY_SLUG_ENV: dict[tuple[str, str], str] = {
    # Examples from spec
    ("monstera-deliciosa", "indoor"): "split_leaf_tropical",
    ("monstera-adansonii", "indoor"): "split_leaf_tropical",
    ("snake-plant", "indoor"): "upright_sword_leaf",
    ("snake-plant-moonshine", "indoor"): "upright_sword_leaf",
    ("pothos", "indoor"): "trailing_vine_green",
    ("philodendron-heartleaf", "indoor"): "trailing_vine_green",
    ("philodendron-brasil", "indoor"): "trailing_vine_variegated",
    ("satin-pothos", "indoor"): "trailing_vine_variegated",
    ("peace-lily", "indoor"): "broadleaf_glossy",
    ("rubber-plant", "indoor"): "broadleaf_glossy",
    ("fiddle-leaf-fig", "indoor"): "rounded_ficus_tree",
    ("fiddle-leaf-fig-bambino", "indoor"): "rounded_ficus_tree",
    ("areca-palm", "indoor"): "palm_feather_indoor",
    ("parlor-palm", "indoor"): "palm_feather_indoor",
    ("boston-fern", "indoor"): "fern_feathery",
    ("maidenhair-fern", "indoor"): "fern_feathery",
    ("jade-plant", "indoor"): "rosette_succulent",
    ("echeveria", "indoor"): "rosette_succulent",
    ("string-of-pearls", "indoor"): "trailing_succulent",
    ("string-of-hearts", "indoor"): "trailing_succulent",
    ("aloe-vera", "indoor"): "spiky_succulent",
    ("pencil-cactus", "indoor"): "spiky_succulent",
    ("clustered-column-cactus", "indoor"): "column_cactus",
    ("barrel-cactus", "indoor"): "barrel_cactus",
    ("bunny-ear-cactus", "indoor"): "pad_cactus",
    ("anthurium", "indoor"): "flowering_tropical",
    ("bromeliad", "indoor"): "flowering_tropical",
    ("african-violet", "indoor"): "flowering_compact",
    ("kalanchoe", "indoor"): "flowering_compact",
    ("caladium", "indoor"): "colorful_foliage",
    ("coleus", "indoor"): "colorful_foliage",
    ("rosemary", "indoor"): "herb_upright",
    ("thyme", "indoor"): "herb_upright",
    ("basil", "indoor"): "herb_mounding",
    ("mint", "indoor"): "herb_mounding",
    ("basil", "outdoor"): "herb_mounding",
    ("mint", "outdoor"): "herb_mounding",
    ("hydrangea-bigleaf", "outdoor"): "flowering_shrub",
    ("hydrangea-panicle", "outdoor"): "flowering_shrub",
    ("rose-knock-out", "outdoor"): "flowering_shrub",
    ("azalea", "outdoor"): "flowering_shrub",
    # Sensible defaults for other common library entries (same archetypes)
    ("zz-plant", "indoor"): "upright_sword_leaf",
    ("spider-plant", "indoor"): "trailing_vine_variegated",
    ("english-ivy", "indoor"): "trailing_vine_green",
    ("philodendron-micans", "indoor"): "trailing_vine_green",
    ("philodendron-xanadu", "indoor"): "split_leaf_tropical",
    ("chinese-evergreen", "indoor"): "broadleaf_glossy",
    ("dieffenbachia", "indoor"): "broadleaf_glossy",
    ("dumb-cane", "indoor"): "broadleaf_glossy",
    ("dumb-cane-camille", "indoor"): "broadleaf_glossy",
    ("aglaonema", "indoor"): "broadleaf_glossy",
    ("ficus-audrey", "indoor"): "rounded_ficus_tree",
    ("ficus-benjamina", "indoor"): "rounded_ficus_tree",
    ("schefflera", "indoor"): "broadleaf_glossy",
    ("money-tree", "indoor"): "broadleaf_glossy",
    ("bird-of-paradise", "indoor"): "broadleaf_glossy",
    ("elephant-ear", "indoor"): "split_leaf_tropical",
    ("alocasia", "indoor"): "split_leaf_tropical",
    ("calathea", "indoor"): "colorful_foliage",
    ("calathea-orbifolia", "indoor"): "colorful_foliage",
    ("rattlesnake-plant", "indoor"): "colorful_foliage",
    ("croton", "indoor"): "colorful_foliage",
    ("ti-plant", "indoor"): "colorful_foliage",
    ("hoya", "indoor"): "trailing_vine_green",
    ("hoya-kerrii", "indoor"): "trailing_vine_green",
    ("string-of-bananas", "indoor"): "trailing_succulent",
    ("burros-tail", "indoor"): "trailing_succulent",
    ("cactus-generic", "indoor"): "column_cactus",
    ("christmas-cactus", "indoor"): "trailing_succulent",
    ("mammillaria-cluster-cactus", "indoor"): "barrel_cactus",
    ("small-column-cactus", "indoor"): "column_cactus",
    ("crown-of-thorns", "indoor"): "spiky_succulent",
    ("panda-plant", "indoor"): "rosette_succulent",
    ("zebra-haworthia", "indoor"): "rosette_succulent",
    ("gasteria", "indoor"): "rosette_succulent",
    ("flaming-katy", "indoor"): "flowering_compact",
    ("lipstick-plant", "indoor"): "flowering_tropical",
    ("norfolk-island-pine", "indoor"): "upright_sword_leaf",
    ("majesty-palm", "indoor"): "palm_feather_indoor",
    ("ponytail-palm", "indoor"): "palm_feather_indoor",
    ("sago-palm", "indoor"): "palm_feather_indoor",
    ("dragon-tree", "indoor"): "upright_sword_leaf",
    ("dracaena-marginata", "indoor"): "upright_sword_leaf",
    ("cast-iron-plant", "indoor"): "upright_sword_leaf",
    ("lavender-indoor", "indoor"): "herb_upright",
    ("sage", "indoor"): "herb_upright",
    ("cuban-oregano", "indoor"): "herb_mounding",
    ("geranium", "indoor"): "flowering_compact",
    ("oxalis", "indoor"): "flowering_compact",
    ("zz-raven", "indoor"): "upright_sword_leaf",
    ("silver-dollar-vine", "indoor"): "trailing_succulent",
    ("arrowhead-plant", "indoor"): "trailing_vine_green",
    ("tradescantia", "indoor"): "trailing_vine_variegated",
    ("peperomia", "indoor"): "broadleaf_glossy",
    ("baby-rubber-plant", "indoor"): "broadleaf_glossy",
    ("silver-philodendron", "indoor"): "trailing_vine_variegated",
    ("prayer-plant", "indoor"): "colorful_foliage",
    ("prayer-plant-lemon-lime", "indoor"): "colorful_foliage",
    ("fittonia", "indoor"): "colorful_foliage",
    ("nerve-plant", "indoor"): "colorful_foliage",
    ("polka-dot-plant", "indoor"): "colorful_foliage",
    ("rex-begonia", "indoor"): "colorful_foliage",
    ("agave", "indoor"): "rosette_succulent",
    ("air-plant", "indoor"): "spiky_succulent",
    ("fatsia-japonica", "indoor"): "broadleaf_glossy",
    ("japanese-aralia", "indoor"): "broadleaf_glossy",
    ("birds-nest-fern", "indoor"): "fern_feathery",
    ("kangaroo-fern", "indoor"): "fern_feathery",
    ("blue-star-fern", "indoor"): "fern_feathery",
    ("clivia", "indoor"): "flowering_compact",
    # Bonsai → compact woody archetype
    ("ficus-bonsai", "indoor"): "rounded_ficus_tree",
    ("juniper-bonsai", "indoor"): "upright_sword_leaf",
    ("japanese-maple-bonsai", "indoor"): "broadleaf_glossy",
    ("jade-bonsai", "indoor"): "rosette_succulent",
    ("pine-bonsai", "indoor"): "upright_sword_leaf",
    ("indoor-bonsai-general", "indoor"): "rounded_ficus_tree",
    # Outdoor: shrubs / trees / herbs / veggies (lightweight defaults)
    ("lavender", "outdoor"): "herb_upright",
    ("creeping-thyme", "outdoor"): "herb_mounding",
    ("tomato", "outdoor"): "herb_mounding",
    ("lettuce", "outdoor"): "herb_mounding",
    ("rosemary", "outdoor"): "herb_upright",
    ("sage", "outdoor"): "herb_upright",
    ("thyme", "outdoor"): "herb_upright",
    ("pepper", "outdoor"): "broadleaf_glossy",
    ("cucumber", "outdoor"): "trailing_vine_green",
    ("carrot", "outdoor"): "herb_mounding",
    ("blueberry", "outdoor"): "flowering_shrub",
    ("strawberry", "outdoor"): "herb_mounding",
    ("raspberry", "outdoor"): "flowering_shrub",
    ("apple-tree", "outdoor"): "rounded_ficus_tree",
    ("peach-tree", "outdoor"): "rounded_ficus_tree",
    ("oak-tree", "outdoor"): "rounded_ficus_tree",
    ("birch", "outdoor"): "rounded_ficus_tree",
    ("red-maple", "outdoor"): "colorful_foliage",
    ("japanese-maple", "outdoor"): "colorful_foliage",
    ("dogwood", "outdoor"): "flowering_shrub",
    ("magnolia", "outdoor"): "flowering_shrub",
    ("boxwood", "outdoor"): "flowering_shrub",
    ("agave", "outdoor"): "rosette_succulent",
    ("yucca", "outdoor"): "upright_sword_leaf",
    ("sedum", "outdoor"): "rosette_succulent",
    ("prickly-pear", "outdoor"): "pad_cactus",
    ("ice-plant", "outdoor"): "trailing_succulent",
    ("black-eyed-susan", "outdoor"): "flowering_compact",
    ("coneflower-echinacea", "outdoor"): "flowering_compact",
    ("sunflower", "outdoor"): "flowering_compact",
    ("petunia", "outdoor"): "flowering_compact",
    ("marigold", "outdoor"): "flowering_compact",
    ("zinnia", "outdoor"): "flowering_compact",
}

_DEFAULT_INDOOR = "broadleaf_glossy"
_DEFAULT_OUTDOOR = "flowering_shrub"


def visual_type_for_slug_env(slug: str, environment: str) -> str:
    env = environment if environment in ("indoor", "outdoor") else "indoor"
    key = (slug, env)
    if key in VISUAL_TYPE_BY_SLUG_ENV:
        return VISUAL_TYPE_BY_SLUG_ENV[key]
    return _DEFAULT_INDOOR if env == "indoor" else _DEFAULT_OUTDOOR
